### ISSUE TITLE
Frontend: Creación de votación

### ISSUE THREAD

**Issue by Virako** [wadobo/votinus#10]
Interfaz de administración donde el administrador podrá crear una votación.

Se necesitará un formulario sencillo donde añadir los campos necesarios para crear una votación y añadir un censo.

**Comment by danigm** [comment]
Acabo de añadir el modelo de votación con un par de acciones para comenzar y terminar una votación. Falta la creación del modelo de censo, en census, que se puede relacionar con la votación con el id, como en la mixnet, para que sea totalmente independiente.
