### ISSUE TITLE
Comprobación de permisos de administrador

### ISSUE THREAD

**Issue by danigm** [wadobo/votinus#19]
Todas las llamadas a API deben ir protegidas tras autenticación, se debe ser administrador para:

- [x] Crear votación
- [x] Iniciar votación
- [x] Parar votación
- [x] Definir censo
- [x] Obtener listado de votos
- [x] Hacer un recuento (shuffle, decrypt)

**Comment by Virako** [comment]
Comprobando estos permisos en la rama auth-perms
