### ISSUE TITLE
Backend: MixNet

### ISSUE THREAD

**Issue by Virako** [wadobo/votinus#4]
La MixNet será una API que se encargará de 3 cosas:

* Barajado: baraja los votos para asegurar el anonimato.
* Generar clave: genera una clave utilizando N autoridades
* Descifrar voto: descifra el voto utilizando N autoridades

Podremos basarnos en una aplicación ya creada con python que nos hace dicho trabajo: https://github.com/danigm/avmixnet

**Comment by danigm** [comment]
Hoy he estado avanzando en esto. He creado una nueva rama llamada mixnet2 y ahí he implementado los modelos y también la creación de una mixnet con varias autoridades.

https://github.com/wadobo/votinus/tree/mixnet2

Para probar lo que he hecho es lanzar dos djangos, uno en el puerto 8000 y otro en el puerto 9000 y lanzar el script test-scripts/test-genkey.sh.

El segundo django lo he lanzado con un settings.py diferente para que tire de otra base de datos.
